"""empty message

Revision ID: 049d6b4dcea7
Revises: 08b83b273b30
Create Date: 2025-06-01 22:17:43.224186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049d6b4dcea7'
down_revision = '08b83b273b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
