"""empty message

Revision ID: 53042f22e21f
Revises: 6f1ab53f04af
Create Date: 2025-06-01 22:42:11.971938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53042f22e21f'
down_revision = '6f1ab53f04af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.String(length=2000), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
